# Generated by Django 4.0.6 on 2022-07-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Churn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelPred', models.FloatField(max_length=100)),
                ('Review', models.FloatField(max_length=100)),
                ('Final', models.FloatField(max_length=100)),
            ],
        ),
    ]
