# Generated by Django 4.1 on 2022-08-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mlmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
    ]
