# Generated by Django 4.1 on 2023-01-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_reviews"),
    ]

    operations = [
        migrations.RenameField(model_name="churn", old_name="Review", new_name="Alt",),
        migrations.AlterField(
            model_name="reviews", name="Alt", field=models.FloatField(max_length=100),
        ),
    ]
