import React,{Component} from "react";
import BuggyCounter from './BuggyCounter';
import MyErrorBoundary from './MyErrorBoundary';
import Navigation from './Navigation';
import './index.css'

export class Home extends Component{
  componentDidMount() {
    window.addEventListener('scroll', this.handleScroll, true);
  }

  componentWillUnmount() {
    window.removeEventListener('scroll', this.handleScroll);
  }

  handleScroll = () => {
    // Here you can add your scroll logic
    console.log('Scrolling!');
  }
  
  render(){
        return(
            <div style={{ backgroundColor: "#00203FFF", color: "#ADEFD1FF " }}>
            <div
              style={{
                display: "flex",
                alignItems: "flex-start",
                padding: "20px",
                animation: "fade-in 2s ease-in",  
              }}
            >
              <img
                src="/leave.png"
                alt="leaving"
                style={{ float: "right", width: "60%", height: "auto", alignSelf: "flex-start", marginLeft:'-20px', marginTop:'-20px' }}
              />
              <div
                style={{
                  textAlign: "left",
                  fontFamily: "'Yesava One', sans-serif",
                  fontSize: "35px", marginTop: '-27.5px'
                }}
              >
                <h3
                  className="justify-content-center"
                  style={{
                    fontWeight: "bold",
                    fontSize: "70px",
                    fontFamily: "Yesava One", marginLeft:'20px'
                  }}
                >
                  Do Customers
                </h3>
                <h3
                  className="justify-content-center"
                  style={{
                    fontWeight: "bold",
                    fontSize: "70px",
                    fontFamily: "Yesava One", marginLeft:'20px'
                  }}
                >
                  Leave Your
                </h3>
                <h3
                  className="justify-content-center"
                  style={{
                    fontWeight: "bold",
                    fontSize: "70px",
                    fontFamily: "Yesava One", marginLeft:'20px'
                  }}
                >
                  Telecom Company?
                </h3>
              </div>
            </div>
            <div className="animation-container animation-slide-in-left"
              style={{
                display: "flex",
                alignItems: "center",
                padding: "20px",
                color: '#E3B448'
              }}
            >
              <div className="animation-text-container" style={{ textAlign: "left", marginRight: "20px" }}>
                <h3 style={{ fontSize: "35px", fontWeight: "bold",
                    fontFamily: "Yesava One", marginTop: '-14px'}}>
                  Our app provides the solution
                </h3>
                <p style={{ fontSize: "20px", fontFamily:'Yesava One', textAlign: 'justify' }}>
                  
In an industry with stiff competition among individual organizations, Churn
 is an important factor to be considered by the company itself as well as by
  prospective customers. In the telecommunication industry, churn can be affected
   by multiple factors: a customer’s preference, their location, their jobs and
    so on. Thus, customer churn in the telecom industry is a widely studied subject.
     However, churn based on previous rates alone is not enough to predict the future churn
      and there must be additional factors considered. We propose a method to overcome this inadequacy.
       By using the predictions generated by past data, a rough estimate of the churn rate for a certain
        time period can be generated, such as a quarter or a year. A Machine Learning algorithm can be used
         for the same to get the value of the prediction. This value can be further tweaked by incorporating
          customer feedback which can affect the churn rate. Thus, the value generated by the predictions and
           the feedback will be more accurate. Check out the Review and Churn Pages.
                </p>
              </div>
              <img
                src="/b.jpg"
                alt="app solution"
                className="animation-image-container"
                style={{ width: "450%", height: "auto", marginTop: "-185px", postion:'fixed', marginRight: '-20px', marginBottom: '-20px' }}
              />
            </div>
          </div>
           
        )
    }
}